### ISSUE TITLE
Catalog category fields items can break JSON if I have ' in items name.

### ISSUE THREAD

**Issue by martins-giberts** [noumo/easyii#103]
Hey,

Firstly Thank you for this awesome CMS. 

I found one minor bug in your fields form:
1. Open Catalog
2. Edit category (as root)
3. Select fields
4. add new/edit existing field, set type to select or checkbox
5. in options try to type in keywords that contain ' like "Palmer's"
6. press save.

If you edited already existing field, it will be deleted. If you made new field it wont be added.

What I did was change <input> to <textarea> and put all the fields JSON in that textarea instead as value="" and problem was solved. Hope this helps.

**Comment by noumo** [comment]
merged pull request, thanks to boehsermoe
