### ISSUE TITLE
The requested URL /easyii/admin/install was not found on this server.

### ISSUE THREAD

**Issue by RGTimothy** [noumo/easyii#116]
This error comes up when I clicked the installation button. Please help. Thanks.

**Comment by boehsermoe** [comment]
What is your full url? Did you add any url rule/pattern in the config?

**Comment by RGTimothy** [comment]
I just do what the instructions says on easyiicms.com. 
![eas1](https://cloud.githubusercontent.com/assets/3026828/13008082/d63c9ea6-d1c6-11e5-8172-6b6b08f7e76a.PNG)

then after i clicked on the installation button:
![eas2](https://cloud.githubusercontent.com/assets/3026828/13008117/f86bab02-d1c6-11e5-9de2-b2a9bcf7d4f7.PNG)

This is my url rule/pattern in the config:
`'urlManager' => [
            'rules' => [
                '<controller:\w+>/view/<slug:[\w-]+>' => '<controller>/view',
                '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
                '<controller:\w+>/cat/<slug:[\w-]+>' => '<controller>/cat',
            ],
        ],`

**Comment by noumo** [comment]
try to install new version
http://easyiicms.com/uploads/files/new.zip

**Comment by RGTimothy** [comment]
umm..its error again after i configure the DB and try to begin the installation
![eas3](https://cloud.githubusercontent.com/assets/3026828/13011355/f075efd6-d1d8-11e5-9d54-a1276bce91f5.PNG)

**Comment by noumo** [comment]
is mod_rewrite enable on your server?

**Comment by RGTimothy** [comment]
yes, its been enabled as phpinfo() tells me so

**Comment by noumo** [comment]
should work.
Try to install easyii on virtualhost, not subfolder of localhost.

**Comment by RGTimothy** [comment]
is this cms should use fxp/composer-asset-plugin:1.0.0? because i'm using 1.1.1 right now

**Comment by RGTimothy** [comment]
ah its working now. I deleted .htaccess, that's why. Thanks.
