### ISSUE TITLE
Не устанавливается

### ISSUE THREAD

**Issue by samatic** [noumo/easyii#121]
Привет. Проблема при установке. Если это shop, выдает сходу "/install/step1 was not found on this server", если старт то "/admin/install was not found on this server". Долго пытался разобраться в чем дело, проблема так и осталась не решенной.

**Comment by noumo** [comment]
Проверьте наличие модуля mod_rewrite

**Comment by samatic** [comment]
Да, после переустановки апача mod_rewrite забыл включить. Включил заработало, спасибо.
