### ISSUE TITLE
/app/views/site/index.php at line 57 Error

### ISSUE THREAD

**Issue by LeonidIvanov** [noumo/easyii#122]
Hello! After installing easyii-shop appeared this problem. Admin panel works great (at least look like) but the front end crashes with fatal error.
`
Error
PHP Fatal Error – yii\base\ErrorException
Call to a member function thumb() on a non-object

    1. in /var/www/gyrosmart/gyrosmart.com.ua/app/views/site/index.php at line 57

    <hr/>
     
     
    <div class="text-center">
        <h2>Last article from category #1</h2>
        <br/>
        <div class="row text-left">
            <?php $article = Article::last(1, ['category_id' => 1]); ?>
            <div class="col-md-2">
line 57:                <?= Html::img($article->thumb(160, 120)) ?>
            </div>
            <div class="col-md-10 text-left">
                <?= Html::a($article->title, ['articles/view', 'slug' => $article->slug]) ?>
                <br/>
                <?= $article->short ?>
            </div>
        </div>
    </div>
     

    2. yii\base\ErrorHandler::handleFatalError()

Apache

Yii Framework/2.0.5-dev

Fatal error: Uncaught exception 'yii\base\ErrorException' with message 'Unknown: open(/var/www/gyrosmart/tmp/sess_365e2eaffdf722c8cefce983d02ac10c, O_RDWR) failed: No such file or directory (2)' in Unknown:0 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleError(2, 'Unknown: open(/...', 'Unknown', 0, Array) #1 {main} thrown in Unknown on line 0
`

**Comment by noumo** [comment]
duplicate
