### ISSUE TITLE
Не удается закешировать контент статичных страниц.

### ISSUE THREAD

**Issue by SpiritAbsolute** [noumo/easyii#123]
Привет! После вызова $page = Page::get($id); не удается закешировать данные $page.
Видимо где то анонимная функция. Ошибка вида: `Serialization of 'Closure' is not allowed.`

**Comment by noumo** [comment]
какая у вас версия php?

**Comment by SpiritAbsolute** [comment]
5.6.18 и 7

**Comment by noumo** [comment]
Попробуйте поставить новую версию
http://easyiicms.com/uploads/files/new.zip

**Comment by SpiritAbsolute** [comment]
Не помогло. Честно говоря, я использую только реализацию статичных страниц вашей cms. И видимо причина в том, что возвращается объект PageObject Object , а он почему то "несереализуется".

**Comment by noumo** [comment]
Не совсем понимаю, откуда и что Вы взяли, пришлите stack trace.

**Comment by SpiritAbsolute** [comment]
Разобрался. Ошибка была в том, что в моей модели было реализовано поведение в котором используется анонимная функция...
