### ISSUE TITLE
Admin previllage

### ISSUE THREAD

**Issue by rpvasanthan** [noumo/easyii#14]
As a root user I can access all the control panel tabs. But as an admin user I can not even add a page. Is it created like this on purpose? It would be great if we have a page in the root user where we can control the admin privillages. If it is not already exists please consider this as a request. Thanks

**Comment by noumo** [comment]
Page module developed as static information pages(about, services, etc), and you can insert it only manually into html as Page::get() and you can`t get the list of pages (for these cases use Article module), so i don`t see any reasons to allow customer(admin) delete or add page.
But page with privillages is good idea.

**Comment by rpvasanthan** [comment]
Thank you
