### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jcvalerio** [noumo/easyii#15]
When I use ```composer create-project noumo/easyii-start cms dev-master```
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for noumo/easyii dev-master -> satisfiable by noumo/easyii[dev-master].
    - noumo/easyii dev-master requires bower-asset/fancybox * -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by noumo** [comment]
Please make sure you have the latest version of composer asset plugin by command 
`composer global require "fxp/composer-asset-plugin:1.0.0"`
