### ISSUE TITLE
Мало примеров

### ISSUE THREAD

**Issue by deniuscoder** [noumo/easyii#17]
Я не могу разобраться, как вновь созданный каталог - отображать на главной странице
куда прописывать:
use yii\easyii\modules\catalog\api\Catalog;

куда 
Catalog::cat(1);
Catalog::cat('cat-slug'); 

и вот это
stdClass Object
(
    [id] => 1
    [title] => "Category name"
    [seo_h1] => "Seo category title"
    [seo_title] => "Seo window title"
    [seo_keywords] => "seo, website, keywords"
    [seo_description] => "Seo description"
    [slug] => "cat-slug"
    [items] => Array
        (
            [0] => stdClass Object
                (
                    [id] => 1
                    [title] => "Item name"
                    [thumb] => "/path/to/thumb.jpg"
                    [description] => "Item description"
                    [slug] => "item-slug"
                    [field1] => "value1"
                    [field2] => "value2"
                    [field3] => "value3"
                )

        )

    [empty] => false
)
понятное дело, что сначала надо понимать как yii работает, но хотелось бы учится сразу на easyii

**Comment by noumo** [comment]
Примеры вы легко можете найти на демо сайте http://demo.easyiicms.com

Для разработки фронтенда Вам понадобятся базовые знания архитектуры MVC и собственно фреймворка Yii 2
Документацию на yii2 можно глянуть здесь
http://www.yiiframework.com/doc-2.0/guide-index.html

Если уж совсем плохо с английским есть незаконченный перевод здесь
https://github.com/yiisoft/yii2/tree/master/docs/guide-ru

Умение создавать контроллеры и представления с помощью yii2 это минимальные требования для работы с EasyiiCMS.

**Comment by deniuscoder** [comment]
Благодарствую!
