### ISSUE TITLE
Install form target url error

### ISSUE THREAD

**Issue by dwater** [noumo/easyii#190]
"Url::to('/admin/install')" should be changed to "Url::toRoute('/admin/install')" in file easyii/views/install/_form.php.

**Comment by Saraylu** [comment]
Very thanks for developers efforts

But next,

I have the same problem. I changed `Url::to('/admin/install')` to `Url::to(['/admin/install'])`
if we want install easyii to sub folder like `mysite.com/easyii` images of articles and . . . will not laod.
some lines are:
vendor/noumo/easyii/helpers/Image.php Line:35:
`$thumbWebFile = '/' . Upload::$UPLOADS_DIR . '/thumbs/' . $thumbName;`
I replaced with:
`Yii::getAlias('@web') .'/'. Upload::$UPLOADS_DIR . '/thumbs/' . $thumbName;`

vendor/noumo/easyii/modules/gallery/api/PhotoObject.php Line:17:
`$a = Html::a($img, $this->image, [`
I replaced with:
`$a = Html::a($img, Yii::getAlias('@web').$this->image, [`

`vendor/noumo/easyii/modules/carousel/views/a/index.php Line:31`

There are many lines. at last i create a virtual host, for solving these issues.
For installing easyii on localhost, must be make a virtualhost
