### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by ifrin** [noumo/easyii#20]
I think it'll be more effective to support code in future, if folder structure of this project'll be like that:

```
app
	config
	controllers
	messages
	migrations
	models
	modules
	runtime
	vendor
	views
	yiic.php
www
	assets
	favicon.ico
	index.php
```

**Comment by noumo** [comment]
Do you mean folder sructure in easyii-start project? 
Its only an example and you can build your application as you wish, because EasyiiCMS works as module and only requires some config options.

**Comment by ifrin** [comment]
Ops, sorry! Yes, I mean easyii-start project, but if it only an example, that's no problem :)
