### ISSUE TITLE
Duplicate slugs

### ISSUE THREAD

**Issue by Viniter** [noumo/easyii#24]
When a new item is being created, with slug being *manually* entered, it doesn't check whether the slug already exists. After submitting the item a database exception is thrown. This happens with most modules I tried, except for the *News* module, which appends the slug with a number.

Not sure what behaviour should be used, number appending is not bad, but user is not notified about the change to his manually entered slug, and may stay under the impression he knows what the slug is. A message saying "This slug is already in use." might be a better solution. Number appending can be left for the auto-generated slugs.

**Comment by noumo** [comment]
Solved this exception and made code much easier, but new issue appeared when you enter dublicated title, error pops on slug input. Thats why now thinking about to make title attribute unique. @Viniter your opinion?

**Comment by Viniter** [comment]
That's no good... unique titles are pointless restriction for the user. Especially with things like news, recurring titles are pretty common. That's what slugs are for – unique identification. Is there no other solution to the problem?

**Comment by Viniter** [comment]
I just tested the new commit. Is the issue that when a duplicate title is entered, user is prompted to change the slug (i.e. the message "Slug ... has already been taken." appears)? I would say in this scenario, it would be appropriate to append the number as you did before.

You have to distinguish between user entering slug manually (they want to have full control over the slug) and slug being filled out automatically (user doesn't care about slug in this scenario).

**Comment by noumo** [comment]
`You have to distinguish between user entering slug manually (they want to have full control over the slug) and slug being filled out automatically (user doesn't care about slug in this scenario).`
This alhorithm worked before but he's very tangled and didn`t work properly in couple with SluggableBehavior.
I think, enable option "ensureUnique" in http://www.yiiframework.com/doc-2.0/yii-behaviors-sluggablebehavior.html is best solution for this case, but user will not see that their slug is not unique, number will always append( cases with dublicate slugs is very rare )

**Comment by Viniter** [comment]
I guess that'll work... I might revisit this issue later, but for now the important thing is it doesn't crash on DB error any more.
