### ISSUE TITLE
Feedback answer messages

### ISSUE THREAD

**Issue by Viniter** [noumo/easyii#25]
Sending answers in feedback module don't seem to work properly.
After trying to send the answer alert "An error has occurred" flashes. 
I'm not sure if the problem is on my side, but both admin, and robot email are correctly filled in, so I don't see where could the problem be. Does it work for you?

Also as a side note, the subject line of the message should definitely be editable. It can be pre-filled like the message, but user should be able to change it.

**Comment by noumo** [comment]
Just checked feedback answer send and recieved an email message, all works fine.
Did you tested on local server? Your SwiftMailer config is correct?
"An error has occurred" flashes only flashes when `http://www.yiiframework.com/doc-2.0/yii-mail-basemessage.html#send()-detail` returns false and unfortunately this class doesn`t provide any error catching on send.

**Comment by Viniter** [comment]
Ok, then, it'll probably be a local server problem. Just wanted to check. 
I noticed that class just returns false, bit unfortunate in terms of debugging...

Anyway, consider adding the subject line input box.
