### ISSUE TITLE
Hard fixed pathes in config

### ISSUE THREAD

**Issue by Chiliec** [noumo/easyii#3]
Installation is not in the root folder impossible. `basePath`, `runtimePath`, `vendorPath` have [aliases in Yii2](http://www.yiiframework.com/doc-2.0/guide-concept-aliases.html).

**Comment by noumo** [comment]
Do you mean config in noumo/easyii-start?
By default yes, you cant, but if you want to do it- just change

'runtimePath' => $_SERVER['DOCUMENT_ROOT'] . '/runtime',
TO
'runtimePath' => $_SERVER['DOCUMENT_ROOT'] . '/YOUR_FOLDER/runtime',

Anyway you can build frontend as you wish, easyii-start is just example
