### ISSUE TITLE
Where is the web folder and how to get it back?

### ISSUE THREAD

**Issue by germansokolov13** [noumo/easyii#30]
Why are accessible and non-accessible files mixed together in the same folder instead of using separate web folder for everything that's accessible? `.htaccess` is a feature of Apache and it might create difficulties for other http-servers.

**Comment by noumo** [comment]
Do you mean easyii-start project? 
Its only an app example and designed to be able to install on cheapest shared hosting.
Easyii created as yii2 module and requires few config options wich you can find in config/easyii.php.

**Comment by auzadventure** [comment]
I agree it should be separated.
