### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by vnenkpet** [noumo/easyii#38]
You have said you are not going to support the current version after merging from the test branch. Can we use git tags (like v1.0.0, v2.0.0) so the users can choose what version to get from composer that it doesn't accidentally break anything in their codebase?

**Comment by noumo** [comment]
Yes, its a good idea, but im not decided yet, wich numbers i should assign to old and new versions. Thinking about 0.8 and 0.9.
Now new version in state of testing, and i need to write new docs, coz a lot of api changed.

**Comment by vnenkpet** [comment]
Why not just use the tags you have in https://github.com/noumo/easyii/blob/master/CHANGELOG.md ?
If the next version is a rewrite, 2.0 will probably be the most correct

**Comment by noumo** [comment]
In normal case you are right. But easyii project is very young (only 3 months) and release version 2.0 in this short period........
Its my bad, coz im newbie in opensource, and unfortunately i didnt decide to start from version 0.1 - 0.9, i released 1.0 and misled users, coz every one thinks that version 1.0+, or 2.0 is stable... But first version was very crude and not enought tested. Now im breaking a backward compatibility, so i think that downgrade version number to 0.8-0.9 is a good idea.

**Comment by vnenkpet** [comment]
Ok. But please do it to prevent compatibility breaks. I recommend tagging the current master 0.8.0 and the current test branch 0.9.0-dev 
Based on http://qpleple.com/understand-composer-versions/

**Comment by noumo** [comment]
i created tags
