### ISSUE TITLE
Numeric slug error

### ISSUE THREAD

**Issue by Chiliec** [noumo/easyii#4]
When title consists of only numeric characters and slug not fill, form clearing and take error: `Create error. Slug is invalid.` 
When fill slug using only numeric characters: `Slug is invalid.`, but at least it checked on the client and data isn't lost. 
May be better to use [SluggableBehavior](http://www.yiiframework.com/doc-2.0/yii-behaviors-sluggablebehavior.html)?

**Comment by noumo** [comment]
yes, because i made that slug cannot starts with numerical...
Didnt know about SluggableBehavior, good idea thank you.

**Comment by noumo** [comment]
solved
