### ISSUE TITLE
Error in Category Model

### ISSUE THREAD

**Issue by vnenkpet** [noumo/easyii#40]
in the test branch, whenver you try to access module which uses categories
http://dl2.joxi.net/drive/0006/1425/402833/150522/16b7e27b00.png

**Comment by noumo** [comment]
strange table name `category_model`, cant find such string in my project, did you edit anything?

**Comment by vnenkpet** [comment]
No. I just installed it from the composer using the test branch and it gave me this error right after installation. I think it's somehow being parsed from the ```CategoryModel``` class name instead of calling children's ```tableName``` method.

**Comment by noumo** [comment]
Which php version you are using?
I think its a php config or strict issue.
I made a small commit, please update and try again.

**Comment by vnenkpet** [comment]
I am using PHP Version 5.5.9-1ubuntu4.9
The bug is still present after update

**Comment by noumo** [comment]
On my windows and ubuntu servers i havent this issue, need some way to reproduce it, or you can try to find solution.
For any questions contact me via skype on `live:noumohope`

**Comment by vnenkpet** [comment]
Well, have you tried it directly after installing by composer and with new database? I just tried both 
```composer create-project noumo/easyii-start easyii-test dev-test```
```composer create-project noumo/easyii-shop easyii-test dev-test``` 
And both are giving me this error... Haven't tried on anything else than my Ubuntu yet though. Gonna try later

**Comment by noumo** [comment]
solved this issue
