### ISSUE TITLE
Is it possible to change the root password on your website?

### ISSUE THREAD

**Issue by delphiserg** [noumo/easyii#48]
Is it possible to change the root password on your website?

**Comment by noumo** [comment]
yes
https://github.com/noumo/easyii/issues/18

**Comment by delphiserg** [comment]
In what section it can be done?

**Comment by noumo** [comment]
it is a sql command, you can do it in any MySQL client, (e.g. phpMyAdmin, Navicat)

**Comment by delphiserg** [comment]
Password encrypted. What algorithm?

**Comment by noumo** [comment]
```
UPDATE `easyii_settings` SET `value` = SHA1(CONCAT( 

    'NEW_PASSWORD',
    
    (SELECT * FROM(SELECT `value` FROM `easyii_settings` WHERE `name` = 'root_auth_key') as a), 
    (SELECT * FROM(SELECT `value` FROM `easyii_settings` WHERE `name` = 'password_salt') as b) 
)) 
WHERE `name` = 'root_password' LIMIT 1;
```

You don't need it, just change `NEW_PASSWORD` to your new password and execute command.

**Comment by delphiserg** [comment]
Thanks. Maybe need add this solution to documentation.

**Comment by noumo** [comment]
good idea
