### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by rahulk-k** [noumo/easyii#54]
Warning: require(C:/xampp/htdocs/vendor/noumo/easyii/config/easyii.php): failed to open stream: No such file or directory in C:\xampp\htdocs\shop\app\config\web.php on line 76

Fatal error: require(): Failed opening required 'C:/xampp/htdocs/vendor/noumo/easyii/config/easyii.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\shop\app\config\web.php on line 76
---------------------------------------------------------------------------------------------------------------------------
C:\xampp\htdocs\shop\app\config\web.php 

Line NO  76 is 
---------------------------------
return array_merge_recursive($config, require($_SERVER['DOCUMENT_ROOT'] . '/vendor/noumo/easyii/config/easyii.php'));

**Comment by noumo** [comment]
Is file `C:/xampp/htdocs/vendor/noumo/easyii/config/easyii.php` exists? And search where he is on your PC.
