### ISSUE TITLE
Index.php at the root folder

### ISSUE THREAD

**Issue by TheSaturn** [noumo/easyii#60]
Hi! You have a serious fault: index.php for web in the same folder with controller, model, etc. it MUST be outside of them. please move it with assets and other files into /web folder like in yii2 advanced template

**Comment by noumo** [comment]
Hi, EasyiiCMS is for creating simple websites and I designed my example apps to be able to setup on chipest shared hosting where you cannot configure virtual host directory.
Anyway easyii is just a yii2 module and you can install in on your yii2-basic application.

P.S. all contorllers, vendor etc. protected by .htaccess file.
