### ISSUE TITLE
Calling unknown method: News::thumb()

### ISSUE THREAD

**Issue by evgenmil** [noumo/easyii#61]
При показе последних новостей News::last(), а также показе News::thumb(100, 100), появляется ошибка
Calling unknown method: yii\easyii\modules\news\models\News::thumb()

Если  ($i >= 2) { News::last($i) } , то ошибка пропадает.

**Comment by noumo** [comment]
Вы используете версию 0.9 ? если да,  то там переработан вызов иконок подробнее можете прочитать здесь: 
http://yiiframework.ru/forum/viewtopic.php?f=9&t=22079&start=140#p153204

Примеры использования можно глянуть в https://github.com/noumo/easyii-shop

**Comment by evgenmil** [comment]
Да, использую версию 0.9. Если выводить одну последнюю новость News::last(1), то ошибка сохраняется.

**Comment by noumo** [comment]
Не совсем понятно как вы вызываете, скиньте пример.
Правильные вызовы:
`News::last()->thumb(100, 100);`
и в случае выборки нескольких последних новостей:
`foreach(News::last(3) as $news) echo $news->thumb(100, 100);`

**Comment by evgenmil** [comment]
Да, именно так:
```
$count = 1;
$news = News::last($count);
                        foreach ($news as $item) : ?>
                                <?php if (!empty($item->image)) : ?>
                                    <?= Html::img($item->thumb(100, 100), ['style' => 'float: left;margin-right: 15px;', 'alt' => $item->title]) ?>
                                <?php endif; ?>
                                <?= Html::a($item->title, ['novosti', 'slug' => $item->slug], ['class' => 'a3', 'title' => $item->title]) ?>
                                <?= Html::tag('div', $item->date, ['class' => 'small-muted']) ?>
                                <?= Html::tag('p', $item->short) ?>
                        <?php endforeach; ?>
```
Вот, если $count > 1, то все ок, если равно 1, то ошибка:
`Calling unknown method: News::thumb()`

**Comment by noumo** [comment]
Если ваш $count > 1 то News::last отдает массив объектов.
Если $count == 1 то News::last отдает сразу объект, не в массиве, поэтому корректный вызов будет News::last()->thumb(100, 100);

**Comment by evgenmil** [comment]
) Что-то я не догадался заглянуть в `easyii/modules/news/api/News.php`
Но почему сделано так? Ведь количество выводимых новостей может регулироваться конечным пользователем.
```
        if($limit > 1){
            return $result;
        } else {
            $this->_last = count($result) ? $result[0] : null;
            return $this->_last;
        }
```
Почему бы просто не отдавать `return $result;` ?

**Comment by noumo** [comment]
EasyiiCMS была создана для разработки простых сайтов, не требующих регистрации и я не предполагал, что посетитель сможет регулировать кол-во последних новостей.
Для решения вашей проблемы, Вы можете сделать форк и внести изменения в код easyii, или небольшой костылек у себя в представлении :)

**Comment by evgenmil** [comment]
Не то, чтобы простым пользователем, имел ввиду, модератором)

**Comment by evgenmil** [comment]
Спасибо за поддержку!
