### ISSUE TITLE
Installing in subdirectory of webroot makes installation fail

### ISSUE THREAD

**Issue by SeeDoubleYou** [noumo/easyii#68]
The form on admin/install has the action set to admin/install. Since the there is no base tag set it will point to [serverroot]/admin/install, which doesn't necessarily have to be the case (usually isn't)

**Comment by SeeDoubleYou** [comment]
This is caused by an error in /easyii/views/install/_form.php where line 6 reads
`<?php $form = ActiveForm::begin(['action' => Url::to('/admin/install')]); ?>`
instead of
`<?php $form = ActiveForm::begin(['action' => Url::to(['/admin/install'])]); ?>`

**Comment by noumo** [comment]
Thank you, fixed.
