### ISSUE TITLE
Don't show images in my webpage

### ISSUE THREAD

**Issue by yborly** [noumo/easyii#73]
HI easyiishop how can i config my project for my images  in my webpage to work
![easyiishop](https://cloud.githubusercontent.com/assets/13325254/8879477/d8457692-325b-11e5-9f83-ca9a8ab54a8d.PNG)

**Comment by noumo** [comment]
try to install in webroot of some virtual host, not in subfolder.

**Comment by githubjeka** [comment]
@yborly if your site hostes in subfolder then you should configurate httaccess and `<base` tag:

in `app/views/layouts/base.php` add to `head`:

```html
 <head>      
        <base href="http://localhost/fulldome/"
```

.htaccess:

```bash
Options +FollowSymLinks
IndexIgnore */*

RewriteEngine on

RewriteBase /fulldome/ # <----ADD HERE

# if a directory or a file exists, use it directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

# otherwise forward it to index.php
RewriteRule . index.php
```

**Comment by chapskev** [comment]
I think @githubjeka it would be better if we could have  uploadPath and uploadUrl param set up on config/params.php
