### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by meizoev** [noumo/easyii#78]
sory for my bad english,
i try to install both of the easyii, start and shop.
for the start its success installation but when i try to setup the second (easyii-shop) i got this msg

"An Error occurred while handling another error:
exception 'yii\base\InvalidConfigException' with message 'The table does not exist: easyii_shopcart_orders' "

thanks..

**Comment by noumo** [comment]
Are you trying to install shop in same database?

**Comment by meizoev** [comment]
same database? no.

first i try the "start" succed installation... then i try to install the "shop" offcourse different database .. and i failed in step 2. and got this message ...

"An Error occurred while handling another error:
exception 'yii\base\InvalidConfigException' with message 'The table does not exist: easyii_shopcart_orders' "... there is any possible (sory my english not good) somethingwrong in the migrations file?

thanks

**Comment by noumo** [comment]
Are you installed from archive or via composer, try composer installation.

**Comment by DenizarSouza** [comment]
Hello, I installed the CMS via composer, but when I open it in the browser it does not appear control panel and if I click install it directs you to this path: "http://localhost/start/admin/install/" but it does not the admin folder.

**Comment by meizoev** [comment]
i dont like composer.. now solved.. i used the first database and installation finished

**Comment by sumit147852** [comment]
When going from Step 2 to Step 3 of installation, the script fails. I believe it goes to a wrong URL.

**Comment by ketanvekariya** [comment]
Like @sumit147852 i had same issue  When going from Step 2 to Step 3 of installation, the script fails. I believe it goes to a wrong URL.

http://localhost/admin/install
It lead me to 404
