### ISSUE TITLE
 Problems installing the admin module

### ISSUE THREAD

**Issue by DenizarSouza** [noumo/easyii#85]
Hello. I installed EasyiiCMS but I couldn't install the Administration Module. I would like to know how could I install it for open the control panel on the homepage?

**Comment by noumo** [comment]
"Administration Module" is a part of EasyiiCMS.
Try to access http://yourhost.com/admin

**Comment by DenizarSouza** [comment]
This is the issue, says there is no admin folder.

**Comment by noumo** [comment]
You should learn basics of yii2,
http://www.yiiframework.com/doc-2.0/guide-structure-modules.html
