### ISSUE TITLE
An internal server error occurred.   when install/step1

### ISSUE THREAD

**Issue by aimchina** [noumo/easyii#89]

**Comment by rubahjantan** [comment]
I got this error,
Not Found.
The requested URL /.../install/step1 was not found on this server. I tried to another server it works, but when i submit installation form, appear error  url : "admin/install" not found. Is there something wrong with my apache configuration or my .htaccess file?

**Comment by noumo** [comment]
check you have installed mod_rewrite and try to install on virtual host, not in subfolder.

**Comment by rubahjantan** [comment]
ok, thank you, i will try
