### ISSUE TITLE
Deletion of copied modules leaves behind folders and files

### ISSUE THREAD

**Issue by Xoduz** [noumo/easyii#91]
If you use the copy module feature to create a copy of a module, easyii will create the required folder and files for said module in the app\modules\ folder, but upon deletion of such a copied module the folder and files are all left behind, and are not deleted. Seems like an oversight, unless this is intended behavior?

**Comment by noumo** [comment]
Module deletion is only removes entry in database table to not display you module in list. I dont think that delete module folder is a good idea.
