### ISSUE TITLE
Redactor plugin not working

### ISSUE THREAD

**Issue by dinhtin** [noumo/easyii#96]
please help me

**Comment by martins-giberts** [comment]
What were you trying to do? 
What happened?
What was expected?

**Comment by dinhtin** [comment]
(Excuse my bad English!)
i install easyiicms 
in module http://demo.easyiicms.com/admin/news/
i write in view like

<?= $form->field($model, 'text')->widget(Redactor::className(),[
    'options' => [
        'minHeight' => 400,
        'imageUpload' => Url::to(['/admin/redactor/upload', 'dir' => 'news']),
        'fileUpload' => Url::to(['/admin/redactor/upload', 'dir' => 'news']),
        'plugins' => ['fullscreen']
    ]
]) ?>

i hope like https://imperavi.com/redactor/plugins/fullscreen/
but not thing happen :(
thanks!!!
