### ISSUE TITLE
Same result when calling multiple Article::items

### ISSUE THREAD

**Issue by rubahjantan** [noumo/easyii#97]
I put on my site simple two category articles, 
'Featured' and popular, 
This my code to call featured and popular article

$featured = Article::items([
...
'tags' => 'featured',
...
]);

$popular = Article::items(
..
'orderBy' => ['views' => SORT_DESC],
...
);

$featured and popular will return same result. I remove the condition "if (!$this->_items)" in file vendor/noumo/easyii/modules/article/api/Article.php, function api_items();

it will return expected result,

**Comment by noumo** [comment]
fixed it in last commit in dev branch
