### ISSUE TITLE
Unable to locate message source for category 'easyii/catalog'.

### ISSUE THREAD

**Issue by 6insanes** [noumo/easyii#98]
Hello! Sorry for my bad English.

When I try to validate Item model form @easyii\modules\catalog\models I get this error. Do you define anywhere except @easyii/config/easyii.php message categories for i18n component? If no and this is a bug I can prepare pull request. And thank you, @noumo, for this great job!

**Comment by noumo** [comment]
Мой не многим лучше :)
Зачем и где вне админки вы пытаетесь валидировать форму товара?
Чтобы подгрузить переводы можете выполнить команду
`\yii\easyii\components\Module::registerTranslations('catalog');`

**Comment by 6insanes** [comment]
Спасибо за ответ!
Я пытаюсь валидировать ItemSearch, который наследуется от Item и реализует логику фильтра для формы (как описано, например, в [этой](http://www.yiiframework.com/wiki/653/displaying-sorting-and-filtering-model-relations-on-a-gridview/) статье).

**Comment by noumo** [comment]
Понял, но лучше сделать свою форму и использовать встроенный в АПИ механизм поиска, тем более что он позволяет искать по доп. полям.

**Comment by 6insanes** [comment]
Ок, я понял. Спасибо за разъяснение!

Еще о наболевшем. Можно ли добавить возможность перетаскивать Item в админке из одной категории в другую? Или я просто не нашел ее? Не удобно каждый раз удалять и создавать Item, если ты его в не ту категорию занес.

Или для этого вопроса создать отдельный тред? Так же могу подготовить пул реквест. Спасибо.

**Comment by noumo** [comment]
Да, такой функционал был бы полезен. можно сделать.

**Comment by 6insanes** [comment]
Как именно, по твоему мнению, это должно выглядить? Еще одно поле в item/edit в виде dropDown? Или как?

**Comment by noumo** [comment]
Что то вроде того, только еще надо отфильтровать категории в которых дополнительные поля не совпадают с редатиктируемым товаром.

**Comment by noumo** [comment]
реализовал в dev ветке
